application: text-n
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
  login: required
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: django
  version: "1.4"
